apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: hello-kubernetes
  spec:
  defaultBackend:
    service:
      name: hello-kubernetes
      port:
        number: 80
  rules:
    - host: 143.198.241.125.nip.io
      http:
        paths:
          - backend:
              service:
                name: hello-kubernetes
                port:
                  number: 80
            path: /hello
            pathType: Prefix
